"""update review schema

Revision ID: 355d9a507ef2
Revises: a30b543ed83f
Create Date: 2025-11-27 16:50:41.680365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '355d9a507ef2'
down_revision: Union[str, Sequence[str], None] = 'a30b543ed83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TABLE IF EXISTS review_detail")
    op.alter_column('action_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('review', 'quality_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('review', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('review', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_constraint(op.f('review_ibfk_1'), 'review', type_='foreignkey')
    op.drop_column('review', 'user_id')
    op.drop_column('review', 'status')
    op.alter_column('review_category_result', 'score',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('review_category_result', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('review_category_result', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('review_meta', 'actor',
               existing_type=mysql.VARCHAR(length=64),
               server_default=None,
               existing_nullable=False)
    op.alter_column('review_meta', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('review_meta', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('review_meta', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review_meta', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review_meta', 'actor',
               existing_type=mysql.VARCHAR(length=64),
               server_default=sa.text("'legacy'"),
               existing_nullable=False)
    op.alter_column('review_category_result', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review_category_result', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review_category_result', 'score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.add_column('review', sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'done'"), nullable=False))
    op.add_column('review', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('review_ibfk_1'), 'review', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.alter_column('review', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('review', 'quality_score',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('action_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.create_table('review_detail',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('issue_category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('issue_severity', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('issue_summary', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('issue_details', mysql.TEXT(), nullable=True),
    sa.Column('issue_line_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('issue_column_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name=op.f('review_detail_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_review_detail_review_id'), 'review_detail', ['review_id'], unique=False)
    op.create_index(op.f('ix_review_detail_id'), 'review_detail', ['id'], unique=False)
    # ### end Alembic commands ###
