"""change review_meta.audit to datetime

Revision ID: 588187a3bfee
Revises: 355d9a507ef2
Create Date: 2025-11-27 17:23:45.026235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '588187a3bfee'
down_revision: Union[str, Sequence[str], None] = '355d9a507ef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_column('review', 'updated_at')
    op.drop_column('review', 'created_at')
    op.drop_column('review_category_result', 'updated_at')
    op.drop_column('review_category_result', 'created_at')
    op.alter_column('review_meta', 'audit',
               existing_type=mysql.JSON(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_review_meta_github'), 'review_meta', type_='foreignkey')
    op.drop_column('review_meta', 'updated_at')
    op.drop_column('review_meta', 'created_at')
    op.drop_column('review_meta', 'actor')
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.add_column('review_meta', sa.Column('actor', mysql.VARCHAR(length=64), nullable=False))
    op.add_column('review_meta', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('review_meta', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.create_foreign_key(op.f('fk_review_meta_github'), 'review_meta', 'users', ['github_id'], ['github_id'])
    op.alter_column('review_meta', 'audit',
               existing_type=sa.DateTime(timezone=True),
               type_=mysql.JSON(),
               existing_nullable=True)
    op.add_column('review_category_result', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('review_category_result', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('review', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('review', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.alter_column('action_log', 'timestamp',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    # ### end Alembic commands ###
