"""add review fields for llm spec

Revision ID: 8dff0767a35b
Revises: 4180ef382170
Create Date: 2025-11-14 16:51:34.578688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8dff0767a35b'
down_revision: Union[str, Sequence[str], None] = '4180ef382170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###

    # 🔹 action_log 는 이 migration에서 전혀 안 건드림

    # --- review 테이블 ---

    # ⚠ 이 필드들은 이미 DB에 있을 수 있으니 add_column 안 함
    # op.add_column('review', sa.Column('language', sa.String(length=50), nullable=False))
    # op.add_column('review', sa.Column('file_path', sa.String(length=255), nullable=False))
    # op.add_column('review', sa.Column('code', sa.Text(), nullable=False))
    # op.add_column('review', sa.Column('global_score', sa.Integer(), nullable=True))
    # op.add_column('review', sa.Column('model_score', sa.Integer(), nullable=True))
    # op.add_column('review', sa.Column('efficiency_index', sa.Float(), nullable=True))

    op.alter_column(
        'review',
        'code_fingerprint',
        existing_type=mysql.VARCHAR(length=64),
        type_=sa.String(length=128),
        nullable=True,
    )
    op.alter_column(
        'review',
        'trigger',
        existing_type=mysql.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'status',
        existing_type=mysql.VARCHAR(length=32),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'summary',
        existing_type=mysql.TEXT(),
        nullable=True,
    )
    op.alter_column(
        'review',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'updated_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )

    # 🔹 기존 인덱스 / 유니크 제약은 이 migration에서 손 안 댐
    # op.drop_index(op.f('uq_review_request_hash'), table_name='review')
    # op.create_index(op.f('ix_review_code_fingerprint'), 'review', ['code_fingerprint'], unique=False)
    # op.create_index(op.f('ix_review_id'), 'review', ['id'], unique=False)
    # op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)

    # 🔹 예전 메타 필드들 컬럼 드랍도, 이미 없는 것도 섞여 있어서 전부 스킵
    # op.drop_column('review', 'categories')
    # op.drop_column('review', 'request_hash')
    # op.drop_column('review', 'total_steps')
    # op.drop_column('review', 'scores')
    # op.drop_column('review', 'error_message')
    # op.drop_column('review', 'aspects_json')
    # op.drop_column('review', 'model')
    # op.drop_column('review', 'result_ref')
    # op.drop_column('review', 'next_step')

    # --- review_report / users timestamp & FK 조정 ---
    op.alter_column(
        'review_report',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )
    op.alter_column(
        'review_report',
        'updated_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )

    op.drop_constraint(op.f('fk_review_report_user'), 'review_report', type_='foreignkey')
    op.create_foreign_key(None, 'review_report', 'users', ['user_id'], ['id'])

    op.alter_column(
        'users',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('now()'),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###

    # --- users / review_report 원복 ---
    op.alter_column(
        'users',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_nullable=False,
    )

    op.drop_constraint(None, 'review_report', type_='foreignkey')
    op.create_foreign_key(
        op.f('fk_review_report_user'),
        'review_report',
        'users',
        ['user_id'],
        ['id'],
        onupdate='CASCADE',
        ondelete='SET NULL',
    )
    op.alter_column(
        'review_report',
        'updated_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_nullable=False,
    )
    op.alter_column(
        'review_report',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_nullable=False,
    )

    # --- review 원복용 코드 중, 컬럼 추가/삭제는 전부 스킵 (upgrade에서 안 건드렸으니까) ---
    # op.add_column('review', sa.Column('next_step', ...))
    # op.add_column('review', sa.Column('result_ref', ...))
    # op.add_column('review', sa.Column('model', ...))
    # op.add_column('review', sa.Column('aspects_json', ...))
    # op.add_column('review', sa.Column('error_message', ...))
    # op.add_column('review', sa.Column('scores', ...))
    # op.add_column('review', sa.Column('total_steps', ...))
    # op.add_column('review', sa.Column('request_hash', ...))
    # op.add_column('review', sa.Column('categories', ...))

    # 인덱스도 여기서 건드리지 않음
    # op.drop_index(...)
    # op.create_index(...)

    op.alter_column(
        'review',
        'updated_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'created_at',
        existing_type=mysql.DATETIME(),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'summary',
        existing_type=mysql.TEXT(),
        nullable=False,
    )
    op.alter_column(
        'review',
        'status',
        existing_type=sa.String(length=20),
        type_=mysql.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'trigger',
        existing_type=sa.String(length=20),
        type_=mysql.VARCHAR(length=32),
        existing_nullable=False,
    )
    op.alter_column(
        'review',
        'code_fingerprint',
        existing_type=sa.String(length=128),
        type_=mysql.VARCHAR(length=64),
        nullable=False,
    )
    # ### end Alembic commands ###
