"""review.user_id nullable + action_log.log_id unique

Revision ID: 355ef1df234e
Revises: 2993ec8ed3a4
Create Date: 2025-11-06 10:18:51.362006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '355ef1df234e'
down_revision: Union[str, Sequence[str], None] = '2993ec8ed3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_created_at'), table_name='review')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_action_user_id'), table_name='action_log')
    op.drop_table('action_log')
    op.drop_index(op.f('github_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('github_id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('login', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('avatar_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=False)
    op.create_index(op.f('github_id'), 'users', ['github_id'], unique=True)
    op.create_table('action_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('case_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_action_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_action_user_id'), 'action_log', ['user_id'], unique=False)
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('code', mysql.TEXT(), nullable=True),
    sa.Column('trigger', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('result', mysql.JSON(), nullable=False),
    sa.Column('summary', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_review_user'), onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_created_at'), 'review', ['created_at'], unique=False)
    # ### end Alembic commands ###
